let QUESTIONS=[], progress=JSON.parse(localStorage.getItem("tm_progress")||"{}"), sessions=JSON.parse(localStorage.getItem("tm_sessions")||"[]"), state={questions:[],answers:[],index:0,timed:false,seconds:3600,interval:null,mode:""};
const $=id=>document.getElementById(id);
async function init(){QUESTIONS=await fetch("data/questions.json").then(r=>r.json()); bindTabs(); loadTheme(); renderDashboard();}
function save(){localStorage.setItem("tm_progress",JSON.stringify(progress));localStorage.setItem("tm_sessions",JSON.stringify(sessions));}
function bindTabs(){document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{let s=b.dataset.screen;if(s==="examSetup")showScreen("examSetup");else{showScreen(s);if(s==="dashboard")renderDashboard();if(s==="errors")showErrors();if(s==="stats")renderStats();}})}
function showScreen(id){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));$(id).classList.add("active");document.querySelectorAll(".tab").forEach(t=>t.classList.toggle("active",t.dataset.screen===id));}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function startLearning(n){state.mode="learning";state.questions=adaptive(n);state.answers=Array(state.questions.length).fill().map(()=>[]);state.index=0;state.timed=false;showScreen("exam");renderQuestion()}
function adaptive(n){let scores=QUESTIONS.map(q=>{let p=progress[q.id];if(!p)return {q,s:0};let acc=p.attempts?p.correct/p.attempts:0;let due=p.nextReview&&Date.parse(p.nextReview)<=Date.now();return {q,s:acc+(due?-0.5:0)+(p.confidence||0)*.05}});return scores.sort((a,b)=>a.s-b.s).slice(0,n).map(x=>x.q)}
function startExam(n,timed){state.mode="exam";state.questions=shuffle(QUESTIONS).slice(0,n);state.answers=Array(n).fill().map(()=>[]);state.index=0;state.timed=timed;state.seconds=timed?3600:0;showScreen("exam");startTimer();renderQuestion()}
function beginSelectedExam(){startExam(+$("countSelect").value,$("timed").checked)}
function startTimer(){clearInterval(state.interval);if(!state.timed){$("timer").textContent="";return} state.interval=setInterval(()=>{state.seconds--;updateTimer();if(state.seconds<=0)finishExam()},1000);updateTimer()}
function updateTimer(){let m=Math.floor(state.seconds/60),s=state.seconds%60;$("timer").textContent=`${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`}
function renderQuestion(){let q=state.questions[state.index];$("examMode").textContent=state.mode==="exam"?"PRÜFUNGSSIMULATION":"LERNMODUS";$("progressBar").style.width=((state.index+1)/state.questions.length*100)+"%";$("qMeta").textContent=`${q.category} · Level ${q.difficulty} · Frage ${state.index+1} / ${state.questions.length}`;$("qText").textContent=q.questionText;$("answers").innerHTML="";shuffle(q.answers).forEach(a=>{let b=document.createElement("button");b.className="answer"+(state.answers[state.index].includes(a.id)?" selected":"");b.textContent=a.text;b.onclick=()=>toggleAnswer(a.id);$("answers").appendChild(b)});$("backBtn").disabled=state.index===0;$("nextBtn").textContent=state.index===state.questions.length-1?"Prüfung abgeben":"Weiter"}
function toggleAnswer(id){let arr=state.answers[state.index];state.answers[state.index]=arr.includes(id)?arr.filter(x=>x!==id):[...arr,id];renderQuestion()}
$("backBtn").onclick=()=>{if(state.index>0){state.index--;renderQuestion()}}
$("nextBtn").onclick=()=>{if(state.mode==="learning"){if($("nextBtn").textContent==="Antwort prüfen") revealLearning();else nextQuestion()}else{if(state.index===state.questions.length-1)finishExam();else{state.index++;renderQuestion()}}}
function revealLearning(){let q=state.questions[state.index],ok=isCorrect(q,state.answers[state.index]);record(q,ok);document.querySelectorAll(".answer").forEach(b=>{let a=q.answers.find(x=>x.text===b.textContent);if(a?.correct)b.classList.add("correct");else if(state.answers[state.index].includes(a?.id))b.classList.add("wrong")});$("nextBtn").textContent=state.index===state.questions.length-1?"Fertig":"Nächste Frage";let box=document.createElement("div");box.className="card";box.innerHTML=`<strong>${ok?"Richtig!":"Leider falsch."}</strong><p>${q.explanation}</p><strong>Prüfungs-Merksatz</strong><p>${q.examTip}</p>`;$("answers").after(box)}
function nextQuestion(){if(state.index===state.questions.length-1){showScreen("dashboard");renderDashboard()}else{state.index++;renderQuestion()}}
function isCorrect(q,sel){let c=q.answers.filter(a=>a.correct).map(a=>a.id).sort(),s=[...sel].sort();return JSON.stringify(c)===JSON.stringify(s)}
function record(q,ok){let p=progress[q.id]||{attempts:0,correct:0,incorrect:0,confidence:0};p.attempts++;ok?p.correct++:p.incorrect++;p.confidence=ok?Math.min(5,(p.confidence||0)+1):Math.max(0,(p.confidence||0)-1);let days=ok?[1,3,7,14,30][Math.min(4,p.correct)]:1;p.nextReview=new Date(Date.now()+days*864e5).toISOString();progress[q.id]=p;save()}
function finishExam(){clearInterval(state.interval);let correct=0,answered=0;state.questions.forEach((q,i)=>{let ok=isCorrect(q,state.answers[i]);if(state.answers[i].length)answered++;if(ok)correct++;record(q,ok)});let session={date:new Date().toISOString(),total:state.questions.length,correct,answered};sessions.unshift(session);sessions=sessions.slice(0,50);save();renderResult(session);showScreen("result")}
function renderResult(s){let pct=s.correct/s.total*100;$("score").textContent=`${s.correct} / ${s.total}`;$("scoreText").textContent=`${pct.toFixed(1).replace(".",",")} % · ${s.correct} richtig · ${s.total-s.correct-(s.total-s.answered)} falsch · ${s.total-s.answered} unbeantwortet`;$("resultDetails").innerHTML=`<div class="bar"><i style="width:${pct}%"></i></div><p>Deine Antworten wurden lokal gespeichert und fließen in deine Lernpriorisierung ein.</p>`}
function showErrors(){showScreen("errors");let ids=Object.keys(progress).filter(id=>progress[id].incorrect>0);$("errorIntro").textContent=`${ids.length} Fragen mit mindestens einem Fehler.`;$("errorList").innerHTML=ids.map(id=>{let q=QUESTIONS.find(x=>x.id===id),p=progress[id];return q?`<div class="card erroritem"><strong>${q.questionText}</strong><span>${q.category} · ${p.incorrect} Fehler · ${p.attempts} Versuche</span></div>`:""}).join("")}
function startErrorTraining(){let qs=shuffle(QUESTIONS.filter(q=>progress[q.id]?.incorrect>0)).slice(0,10);if(!qs.length)return alert("Noch keine Fehler vorhanden.");state.mode="learning";state.questions=qs;state.answers=Array(qs.length).fill().map(()=>[]);state.index=0;showScreen("exam");renderQuestion()}
function renderDashboard(){let a=Object.values(progress).reduce((x,p)=>x+p.attempts,0),c=Object.values(progress).reduce((x,p)=>x+p.correct,0);$("accuracy").textContent=a?Math.round(c/a*100)+" %":"0 %";$("answered").textContent=`${a} Fragen`;let weakest=QUESTIONS.map(q=>({q,p:progress[q.id]})).filter(x=>x.p).reduce((m,x)=>{let acc=x.p.correct/x.p.attempts;return !m||acc<m.acc?{q:x.q,acc}:m},null);if(weakest){$("weakTopic").textContent=weakest.q.category;$("weakText").textContent=`Deine aktuelle Leistung liegt bei etwa ${Math.round(weakest.acc*100)} %. Trainiere dieses Thema gezielt.`}}
function renderStats(){let a=Object.values(progress).reduce((x,p)=>x+p.attempts,0),c=Object.values(progress).reduce((x,p)=>x+p.correct,0);let cats=[...new Set(QUESTIONS.map(q=>q.category))];$("statsContent").innerHTML=`<div class="statrow"><b>Fragen beantwortet</b><b>${a}</b></div><div class="statrow"><b>Richtig</b><b>${c}</b></div><div class="statrow"><b>Trefferquote</b><b>${a?Math.round(c/a*100):0} %</b></div><h3>Themen</h3>`+cats.map(cat=>{let qs=QUESTIONS.filter(q=>q.category===cat),ps=qs.map(q=>progress[q.id]).filter(Boolean),aa=ps.reduce((x,p)=>x+p.attempts,0),cc=ps.reduce((x,p)=>x+p.correct,0),pct=aa?Math.round(cc/aa*100):0;return `<div class="statrow"><span>${cat}</span><b>${aa?pct+" %":"–"}</b></div><div class="bar"><i style="width:${pct}%"></i></div>`}).join("")}
function loadTheme(){let dark=localStorage.getItem("tm_dark")==="1";document.documentElement.classList.toggle("dark",dark)}
$("themeBtn").onclick=()=>{let dark=!document.documentElement.classList.contains("dark");document.documentElement.classList.toggle("dark",dark);localStorage.setItem("tm_dark",dark?"1":"0")}
init()
